<h1 style='text-align: center;'>CQF Exam One Report - Harrison King</h1>
<h3 style='text-align: center;'>June 2023 Cohort</h3>

In [41]:
# Install dependencies
import numpy as np
import pandas as pd
import tabulate

## Optimal Portfolio Allocation

An investment universe of the following risky assets with a dependence structure (correlation) applies to all questions below as relevant:

$$\begin{array}{cccc}\text { Asset } & \boldsymbol{\mu} & \boldsymbol{\sigma} & \boldsymbol{w} \\ A & 0.05 & 0.07 & w_{1} \\ B & 0.07 & 0.28 & w_{2} \\ C & 0.15 & 0.25 & w_{3} \\ D & 0.22 & 0.31 & w_{4}\end{array}$$
$$
\text {Corr}=\left(\begin{array}{cccc}
1 & 0.4 & 0.3 & 0.3 \\
0.4 & 1 & 0.27 & 0.42 \\
0.3 & 0.27 & 1 & 0.5 \\
0.3 & 0.42 & 0.5 & 1
\end{array}\right)
$$

### Question 1: 
Global Minimum Variance portfolio is obtained subject to the budget constraint:

$$
\underset{\boldsymbol{w}}{\operatorname{argmin}} \frac{1}{2} \boldsymbol{w}^{\prime} \boldsymbol{\Sigma} \boldsymbol{w} \quad \text { s.t. } \boldsymbol{w}^{\prime}\boldsymbol{1} = 1
$$

**1.1)** Derive the analytical solution for optimal allocations $\boldsymbol{w}^{*}$. Provide full mathematical workings.

**1.2)** In the derivation, include the formula derivation for the Lagrangian multiplier.

**1.3)** Compute optimal allocations (Global MV portfolio) for the given investment universe.

**1.1)** First define the diagonal standard deviation matrix, $\boldsymbol{S}$, is defined as follows:

$$
\boldsymbol{S}=\left(\begin{array}{cccc}
{\sigma}_{A} & 0 & 0 & 0 \\
0 & {\sigma}_{B} & 0 & 0 \\
0 & 0 & {\sigma}_{C} & 0 \\
0 & 0 & 0 & {\sigma}_{D}
\end{array}\right) = \left(\begin{array}{cccc}
                    0.07 & 0 & 0 & 0 \\
                    0 & 0.28 & 0 & 0 \\
                    0 & 0 & 0.25 & 0 \\
                    0 & 0 & 0 & 0.31
                    \end{array}\right)
$$

We can calculate the covariance matrix, $\Sigma$ by pre-multiplying and post-multiplying the correlation matrix, $Corr$ by the diagonal standard deviation matrix, $\boldsymbol{S}$:

$$\Sigma = \boldsymbol{S}Corr\boldsymbol{S} = \left(\begin{array}{cccc}
{\sigma}_{A}^2 & {\rho}_{AB}{\sigma}_{A}{\sigma}_{B} & {\rho}_{AC}{\sigma}_{A}{\sigma}_{C} & {\rho}_{AD}{\sigma}_{A}{\sigma}_{D} \\
{\rho}_{BA}{\sigma}_{A}{\sigma}_{B} & {\sigma}_{B}^2 & {\rho}_{BC}{\sigma}_{B}{\sigma}_{C} & {\rho}_{BD}{\sigma}_{B}{\sigma}_{D} \\
{\rho}_{CA}{\sigma}_{A}{\sigma}_{C} & {\rho}_{CB}{\sigma}_{B}{\sigma}_{C} & {\sigma}_{C}^2 & {\rho}_{CD}{\sigma}_{C}{\sigma}_{D} \\
{\rho}_{DA}{\sigma}_{A}{\sigma}_{D} & {\rho}_{DB}{\sigma}_{B}{\sigma}_{D} & {\rho}_{DC}{\sigma}_{C}{\sigma}_{D} & {\sigma}_{D}^2
\end{array}\right)$$

&nbsp;

Then we can define the Lagrangian function $L(x, \lambda)$ with one multiplier $\lambda$ which represents the budget constraint, $\boldsymbol{w}^{\prime}\boldsymbol{1} = 1 == \boldsymbol{w}\boldsymbol{1}^{\prime} = 1$:

$L(x, \lambda) = \frac{1}{2}\boldsymbol{w}^{\prime}{\Sigma}\boldsymbol{w} + \lambda (1-\boldsymbol{1}^{\prime}\boldsymbol{w})$

&nbsp;

Solving the first order equation of the Lagrangian function we get two partial differential equations:

$\frac{\partial L}{\partial w}(w, \lambda) = \boldsymbol{w}^{\prime}{\Sigma} - \lambda\boldsymbol{1}^{\prime} = 0$

$\frac{\partial L}{\partial \lambda}(w, \lambda) = 1 - \boldsymbol{1}^{\prime}\boldsymbol{w} = 0$

&nbsp;

Then we can define the optimal portfolio allocation $\boldsymbol{w}^{\ast}$ by multiplying $\boldsymbol{w}^{\prime}{\Sigma} - \lambda\boldsymbol{1}^{\prime} = 0$ by the inverse matrix ${\Sigma}^{-1}$:

$\boldsymbol{w}^{\prime}{\Sigma} = \lambda\boldsymbol{1}^{\prime}$

$\therefore \boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{1})$ which we can call the candidate function.

&nbsp;

**1.2)** We can then derive the Lagrangian multiplier $\lambda$ by substituting $\boldsymbol{w}^{\ast}$ into the budget constraint $\boldsymbol{w}\boldsymbol{1}^{\prime} = 1$:

$\boldsymbol{1}^{\prime}{\Sigma}^{-1}(\lambda\boldsymbol{1}) = \lambda\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{1} = 1$

$\therefore \lambda = \frac{1}{\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{1}}$

&nbsp;

Finally, we can define the optimal portfolio allocation $\boldsymbol{w}^{\ast}$ by substituting $\lambda$ into the candidate function $\boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{1})$:

$$\text{Optimial Portfolio Allocation } \boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{1}) = {\Sigma}^{-1}(\frac{1}{\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{1}}\boldsymbol{1})$$

**1.3)** Computing allocations: Define the inputs

In [42]:
# Define the assets, standard deviations vector and correlation matrix
assets = ['A', 'B', 'C', 'D']
std_deviation_vector = np.array([0.07, 0.28, 0.25, 0.31])
correlation_matrix = np.array([[1.0, 0.4, 0.3, 0.3], 
                                 [0.4, 1.0, 0.27, 0.42], 
                                 [0.3, 0.27, 1.0, 0.5], 
                                 [0.3, 0.42, 0.5, 1.0]])

# Define a function that calculates the covariance matrix using the correlation matrix and the standard deviations vector
def calculate_Covariance_Matrix(std_deviation_vector: np.ndarray, correlation_matrix: np.ndarray):
    ''' Calculates the covariance matrix from the standard deviation vector and correlation matrix
    Args:
        std_deviation_vector (np.ndarray): Vector of asset standard deviations
        correlation_matrix (np.ndarray): Correlation matrix of assets
    '''
    return np.outer(std_deviation_vector, std_deviation_vector) * correlation_matrix

covariance_matrix = calculate_Covariance_Matrix(std_deviation_vector, correlation_matrix)
print(f'Covariance Matrix:\n{covariance_matrix}')

Covariance Matrix:
[[0.0049   0.00784  0.00525  0.00651 ]
 [0.00784  0.0784   0.0189   0.036456]
 [0.00525  0.0189   0.0625   0.03875 ]
 [0.00651  0.036456 0.03875  0.0961  ]]


In [43]:
# Initiliase the 1s vector
ones_vector = np.ones(len(assets))

# Calculate the inverse of the covariance matrix (Σ^-1)
inverse_covariance_matrix = np.linalg.inv(covariance_matrix)
print(f'Inverse covariance matrix:\n{inverse_covariance_matrix}\n')

Inverse covariance matrix:
[[256.33078818 -20.50521083 -12.51725725  -4.53831162]
 [-20.50521083  17.21811596  -0.39445138  -4.98365996]
 [-12.51725725  -0.39445138  22.06964258  -7.90146915]
 [ -4.53831162  -4.98365996  -7.90146915  15.78991307]]



Computing allocations: Calculate the Lagrangian Multiplier lambda
$\lambda = \frac{1}{\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{1}}$

In [44]:
# λ = 1 / 1^'.(Σ^-1).1^
lagrangian_lambda = 1 / ones_vector.T.dot(inverse_covariance_matrix).dot(ones_vector)
print(f'λ = {lagrangian_lambda}')

λ = 0.004768086485896823


Computing allocations: Optimal portfolio allocations
$\boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{1})$

In [45]:
# Optimal weights, w* = (Σ^-1).(λ.1^)
optimal_weights = inverse_covariance_matrix.dot(lagrangian_lambda * ones_vector)

# Format the weights and print
formatted_weights = [f'{weight:.2%}' for weight in optimal_weights]
portfolio = dict(zip(assets, formatted_weights))

print(tabulate.tabulate(portfolio.items(), headers=['Asset', 'Weight'], tablefmt='fancy_grid')) 

╒═════════╤══════════╕
│ Asset   │ Weight   │
╞═════════╪══════════╡
│ A       │ 104.31%  │
├─────────┼──────────┤
│ B       │ -4.13%   │
├─────────┼──────────┤
│ C       │ 0.60%    │
├─────────┼──────────┤
│ D       │ -0.78%   │
╘═════════╧══════════╛


### Question 2:

Consider the optimization for a target return $m$. There is no risk-free asset.

$$
\begin{aligned}
& \underset{\boldsymbol{w}}{\operatorname{argmin}} \frac{1}{2} \boldsymbol{w}^{\prime} \boldsymbol{\Sigma} \boldsymbol{w} \\
& \boldsymbol{w}^{\prime} \mathbf{1}=1 \\
& \boldsymbol{w}^{\prime} \boldsymbol{\mu}=m
\end{aligned}
$$

**2.1)** Compute $\mathbf{w}^{*}$ and portfolio risk $\sigma_{\Pi}=\sqrt{\boldsymbol{w}^{\prime} \boldsymbol{\Sigma} \boldsymbol{w}}$ for $m=7 \%$ for three levels of correlation.

**2.2)** Correlation matrix $\times 1, \times 1.3, \times 1.8$, subject to individual correlation upper limit of 0.99 , if the scaling results in correlation value above 1 . Provide all results in a single table.

The vector of returns, $\boldsymbol{\mu}$ is defined as:

$$
\boldsymbol{\mu}=\left(\begin{array}{c}
{\mu}_{A} \\
{\mu}_{B} \\
{\mu}_{C} \\
{\mu}_{D}
\end{array}\right) = \left(\begin{array}{c}
                    0.05 \\
                    0.07 \\
                    0.15 \\
                    0.22
                    \end{array}\right)
$$

In [46]:
# Define the min return, m = 7% and vector of mean returns of the assets, μ
min_return = 0.07

mean_returns_vector = np.array([0.05, 0.07, 0.15, 0.22])

**2.1)** We'll define $\mathbf{w}^{*}$ by solving a new Lagrangian function, $L(x, \lambda, \gamma)$ with two Lagrangian multipliers $\lambda$ and $\gamma$ which represent the budget constraint, $\boldsymbol{w}^{\prime}\boldsymbol{1} = 1 == \boldsymbol{w}\boldsymbol{1}^{\prime} = 1$ and the return constraint, $\boldsymbol{w}^{\prime}\boldsymbol{\mu} = m == \boldsymbol{w}\boldsymbol{\mu}^{\prime} = m$:

Then we can define the Lagrangian function $L(x, \lambda, \gamma)$ as:

$L(x, \lambda, \gamma) = \frac{1}{2}\boldsymbol{w}^{\prime}{\Sigma}\boldsymbol{w} + \lambda(m - \boldsymbol{\mu}^{\prime}\boldsymbol{w}) + \gamma (1-\boldsymbol{1}^{\prime}\boldsymbol{w})$

&nbsp;

Solving the first order equation of the Lagrangian function we get three partial differential equations:

$\frac{\partial L}{\partial w}(w, \lambda, \gamma) = \boldsymbol{w}^{\prime}{\Sigma} - \lambda\boldsymbol{\mu}^{\prime} - \gamma\boldsymbol{1}^{\prime} = 0$

$\frac{\partial L}{\partial \lambda}(w, \lambda, \gamma) = m - \boldsymbol{\mu}^{\prime}\boldsymbol{w} = 0$

$\frac{\partial L}{\partial \gamma}(w, \lambda, \gamma) = 1 - \boldsymbol{1}^{\prime}\boldsymbol{w} = 0$

&nbsp;

Then we can define the optimal portfolio allocation $\boldsymbol{w}^{\ast}$ by multiplying $\boldsymbol{w}^{\prime}{\Sigma} - \lambda\boldsymbol{\mu}^{\prime} - \gamma\boldsymbol{1}^{\prime} = 0$ by the inverse matrix ${\Sigma}^{-1}$:

$\boldsymbol{w}^{\prime}{\Sigma} = \lambda\boldsymbol{\mu}^{\prime} + \gamma\boldsymbol{1}^{\prime}$

$\therefore \boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{\mu} + \gamma\boldsymbol{1})$ which we can call the candidate function.

&nbsp;

Substituting the candidate function, $\boldsymbol{w}^{\ast}$ into our two constraint equations we will try to solve for $\lambda$ and $\gamma$.

First we will substitute $\boldsymbol{w}^{\ast}$ into the budget constraint equation $\boldsymbol{w}\boldsymbol{1}^{\prime} = 1$:

$$\boldsymbol{w}^{\ast}\boldsymbol{1}^{\prime} = 1$$

$$\Rightarrow \boldsymbol{1}^{\prime}{\Sigma}^{-1}(\lambda\boldsymbol{\mu} + \gamma\boldsymbol{1}) = 1$$

$$\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {1}}} \;\;\;\; \Rightarrow \lambda\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{\mu} + \gamma\boldsymbol{1}^{\prime}{\Sigma}^{-1}\boldsymbol{1} = 1$$

Then we will substitute $\boldsymbol{w}^{\ast}$ into the return constraint equation $\boldsymbol{w}\boldsymbol{\mu}^{\prime} = m$:

$$\boldsymbol{w}^{\ast}\boldsymbol{\mu}^{\prime} = m$$ 

$$\Rightarrow \boldsymbol{\mu}^{\prime}{\Sigma}^{-1}(\lambda\boldsymbol{\mu} + \gamma\boldsymbol{1}) = m$$

$$\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {2}}} \;\;\;\; \Rightarrow \lambda\boldsymbol{\mu}^{\prime}{\Sigma}^{-1}\boldsymbol{\mu} + \gamma\boldsymbol{\mu}^{\prime}{\Sigma}^{-1}\boldsymbol{1} = m$$

&nbsp;

For ease of computation we will define the following scalar variables:

$$A = \boldsymbol{1}{\Sigma}^{-1}\boldsymbol{1}$$ 

$$B = \boldsymbol{\mu}^{\prime}{\Sigma}^{-1}\boldsymbol{1} \Rightarrow \boldsymbol{1}{\Sigma}^{-1}\boldsymbol{\mu}$$

$$C = \boldsymbol{\mu}^{\prime}{\Sigma}^{-1}\boldsymbol{\mu}$$

&nbsp;

We can then re-write equations $\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {1}}}$ and $\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {2}}}$ as:

$$\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {1}}} \;\;\;\; B\lambda + A\gamma = 1$$

$$\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {2}}} \;\;\;\; C\lambda + B\gamma = m$$

Rearranging $\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {1}}}$ and $\raisebox{.5pt}{\textcircled{\raisebox{-.8pt} {2}}}$ we define our Lagrangian multipliers, $\lambda$ and $\gamma$, in terms of the constants $A$, $B$, and $C$:

$$\lambda = \frac{Am - B}{AC -{B}^{2}}$$

$$\gamma = \frac{C - Bm}{AC -{B}^{2}}$$

$$\text{Optimial Portfolio Allocation } \boldsymbol{w}^{\ast} = {\Sigma}^{-1}(\lambda\boldsymbol{\mu} + \gamma\boldsymbol{1})$$

**2.2)** Define the scaled correlation matrices as $Corr_{1}$, $Corr_{1.3}$ and $Corr_{1.8}$ respectively. 
$$
\text Corr_{1}=\left(\begin{array}{cccc}
1 & 0.4 & 0.3 & 0.3 \\
0.4 & 1 & 0.27 & 0.42 \\
0.3 & 0.27 & 1 & 0.5 \\
0.3 & 0.42 & 0.5 & 1
\end{array}\right)
$$

$$
\text Corr_{1.3}=\left(\begin{array}{cccc}
1 & 0.52 & 0.39 & 0.39 \\
0.52 & 1 & 0.35 & 0.55 \\
0.39 & 0.35 & 1 & 0.65 \\
0.39 & 0.55 & 0.65 & 1
\end{array}\right)
$$

$$
\text Corr_{1.8}=\left(\begin{array}{cccc}
1 & 0.72 & 0.54 & 0.54 \\
0.72 & 1 & 0.49 & 0.76 \\
0.54 & 0.49 & 1 & 0.9 \\
0.54 & 0.76 & 0.9 & 1
\end{array}\right)
$$

Consequently, the covariance matrices $\Sigma_{1}$, $\Sigma_{1.3}$ and $\Sigma_{1.8}$ are given by:

$$\Sigma_{1} = \boldsymbol{S}Corr_{1}\boldsymbol{S}$$

$$\Sigma_{1.3} = \boldsymbol{S}Corr_{1.3}\boldsymbol{S}$$

$$\Sigma_{1.8} = \boldsymbol{S}Corr_{1.8}\boldsymbol{S}$$

where $\boldsymbol{S}$ is the diagonal matrix of standard deviations of the assets.

&nbsp;

Now we can compute the optimal allocation, $\boldsymbol{w}^{\ast}$ and portfolio risk, ${\sigma}_{\Pi}$ for $m = 7\%$ for each of the three correlation matrices.

In [50]:
# Define a function that uses Lagrange multipliers to find the minimum variance portfolio for a given return
def calculate_Optimal_Lagrangian_Allocations(min_return: float, covariance_matrix: np.ndarray, returns_vector: np.ndarray):
    ''' Calculate the Optimal Portfolio allocations using Lagrangian Multipliers closed form solution
    Args:
        min_return (float) = The minimum or 'target' return required for the portfolio, as a decimal (e.g. 0.1 = 10%)
        covariance_matrix (np.array) = The covariance matrix of the portfolio
        returns_vector (np.array) = The mean returns vector of the portfolio
    Returns:
        optimal_weights (np.array) = The optimal weights for the portfolio
    '''
    # Initiliase the 1s vector
    ones_vector = np.ones(returns_vector.shape[0])

    # Calculate the inverse of the covariance matrix (Σ^-1)
    inverse_covariance = np.linalg.inv(covariance_matrix)

    # Get scalar values to solve the quadratic equation for the two constaint equations -> 1. Sum of weights = 1 and 2. Minimum return
    # A = 1^.(Σ^-1).1^
    A = ones_vector.dot(inverse_covariance.dot(ones_vector))

    # B = 1^.(Σ^-1).μ
    B = ones_vector.dot(inverse_covariance.dot(returns_vector))

    # C = μ'.(Σ^-1).μ
    C = returns_vector.T.dot(inverse_covariance.dot(returns_vector))

    # λ = (A*min_return - B) / (A*C - B^2)
    lagrangian_lambda = (A*min_return - B) / (A*C - B**2)

    # γ = (C - B*min_return) / (A*C - B^2)
    lagrangian_gamma = (C - B*min_return) / (A*C - B**2)

    # Calculate the optimal weights, w* for the portfolio
    # w* = (Σ^-1).(λ.μ + γ.1^)
    optimal_weights = inverse_covariance.dot(lagrangian_lambda * returns_vector + lagrangian_gamma * ones_vector)

    # print(f'A: {A}')
    # print(f'B: {B}')
    # print(f'C: {C} \n')
    # print(f'λ: {lagrangian_lambda}')
    # print(f'γ: {lagrangian_gamma} \n')

    # formatted_weights = [f'{weight:.2%}' for weight in optimal_weights]
    # portfolio = dict(zip(assets, formatted_weights))

    # print(tabulate.tabulate(portfolio.items(), headers=['Asset', 'Weight'], tablefmt='fancy_grid')) 

    return optimal_weights

In [48]:
# Create the scaled correlation matrices
corr_1 = correlation_matrix
corr_1_3 = correlation_matrix * 1.3
corr_1_8 = correlation_matrix * 1.8

# If any correlation is greater than 1, set it to 0.99
corr_1_3[corr_1_3 > 1.0] = 0.99
corr_1_8[corr_1_8 > 1.0] = 0.99

# Set the leading diagonals back to 1.0
np.fill_diagonal(corr_1_3, 1.0)
np.fill_diagonal(corr_1_8, 1.0)

print(f'Correlation Matrix x1: \n{corr_1}\n')
print(f'Correlation Matrix x1.3: \n{corr_1_3}\n')
print(f'Correlation Matrix x1.8: \n{corr_1_8}')

Correlation Matrix x1: 
[[1.   0.4  0.3  0.3 ]
 [0.4  1.   0.27 0.42]
 [0.3  0.27 1.   0.5 ]
 [0.3  0.42 0.5  1.  ]]

Correlation Matrix x1.3: 
[[1.    0.52  0.39  0.39 ]
 [0.52  1.    0.351 0.546]
 [0.39  0.351 1.    0.65 ]
 [0.39  0.546 0.65  1.   ]]

Correlation Matrix x1.8: 
[[1.    0.72  0.54  0.54 ]
 [0.72  1.    0.486 0.756]
 [0.54  0.486 1.    0.9  ]
 [0.54  0.756 0.9   1.   ]]


In [49]:
# Calculate the covariance matrices for each of the correlation matrices
covariance_matrix_1 = covariance_matrix
covariance_matrix_1_3 = calculate_Covariance_Matrix(std_deviation_vector, corr_1_3)
covariance_matrix_1_8 = calculate_Covariance_Matrix(std_deviation_vector, corr_1_8)

# Store the matrices in a list
covariance_matrices = [covariance_matrix_1, covariance_matrix_1_3, covariance_matrix_1_8]

print(f'Covariance Matrix 1: \n{covariance_matrix_1}\n')
print(f'Covariance Matrix 1_3: \n{covariance_matrix_1_3}\n')
print(f'Covariance Matrix 1_8: \n{covariance_matrix_1_8}\n')

Covariance Matrix 1: 
[[0.0049   0.00784  0.00525  0.00651 ]
 [0.00784  0.0784   0.0189   0.036456]
 [0.00525  0.0189   0.0625   0.03875 ]
 [0.00651  0.036456 0.03875  0.0961  ]]

Covariance Matrix 1_3: 
[[0.0049    0.010192  0.006825  0.008463 ]
 [0.010192  0.0784    0.02457   0.0473928]
 [0.006825  0.02457   0.0625    0.050375 ]
 [0.008463  0.0473928 0.050375  0.0961   ]]

Covariance Matrix 1_8: 
[[0.0049    0.014112  0.00945   0.011718 ]
 [0.014112  0.0784    0.03402   0.0656208]
 [0.00945   0.03402   0.0625    0.06975  ]
 [0.011718  0.0656208 0.06975   0.0961   ]]



Find the portfolio risk as $\sigma_{\Pi}=\sqrt{\boldsymbol{w}^{\prime} \boldsymbol{\Sigma} \boldsymbol{w}}$ defining this calculation as a function.

In [54]:
def calculate_Portfolio_Risk(weights: np.ndarray, covariance_matrix: np.ndarray):
    '''Calculate the annualised portfolio risk (standard deviation) given a set of weights
    Args:
        weights (np.ndarray): An array of assets weights
        covariance_matrix (np.ndarray): The covariance matrix of the assets
    Returns:
        annualised_std (float): The annualised portfolio standard deviation'''
    annualised_std = np.sqrt(np.dot(weights.T, np.dot(covariance_matrix, weights))) * np.sqrt(252)

    return annualised_std

In [59]:
# Find optimal portfolio allocations for each correlation matrix using the Lagrangian method using the minimum return of 0.07 and the mean returns vector
optimal_weights = [calculate_Optimal_Lagrangian_Allocations(min_return, covariance_matrix, mean_returns_vector) for covariance_matrix in covariance_matrices]

# Find the corresponding portfolio risk for each set of optimal weights
portfolio_risk = [calculate_Portfolio_Risk(weights, covariance_matrix) for weights, covariance_matrix in zip(optimal_weights, covariance_matrices)]

# Formatting the optimal weights into percentages and column names
formatted_weights = [list(map(lambda x: "{:.2%}".format(x), weights)) for weights in optimal_weights]
formatted_assets = [asset + ' Weight' for asset in assets]

# Create a dataframe representing the portfolios with the optimal weights, portfolio risks and correlation multipliers for each correlation matrix
portfolios_df = pd.DataFrame(formatted_weights, columns=formatted_assets)
portfolios_df['Portfolio Risk'] = portfolio_risk
portfolios_df['Correlation Multiplier'] = [1.0, 1.3, 1.8]
portfolios_df.head()

A Weight B Weight C Weight D Weight  Portfolio Risk  Correlation Multiplier
0   92.41%   -7.29%    5.47%    9.40%        1.228879                     1.0
1   99.65%  -13.51%    1.24%   12.62%        1.214177                     1.3
2  145.09%  -40.77%  -50.71%   46.39%        0.654712                     1.8

## Understanding Risk

**Question 3.** "Evaluating the P\\&L more frequently make it appear more risky than it actually is." Make the following simple computations to demonstrate this statement.

- Write down the formula for Sharpe Ratio and identify main parameter scaled with time.
- Compute Daily, Monthly, and Quarterly Sharpe Ratio, for Annualised SR of 0.53. No other inputs.
- Convert each Sharpe Ratio into Loss Probability (daily, monthly, quarterly, annual), using

$$
\operatorname{Pr}(\mathrm{P} \& \mathrm{~L}<0)=\operatorname{Pr}(x<-\mathrm{SR}) .
$$

where $x$ is a standard Normal random variable.

**Question 4.** Instead of computing the optimal allocations analytically, let's conduct an experiment. Generate above 700 random allocation sets: $4 \times 1$ vectors. Those will not be optimal and can be negative.

- Standardise each set to satisfy $w^{\prime} \mathbf{1}=1$. In fact, generate 3 allocations and compute the 4 th.
- For each set, compute $\mu_{\Pi}=\boldsymbol{w}^{\prime} \boldsymbol{\mu}$ and $\sigma_{\Pi}=\sqrt{\boldsymbol{w}^{\prime} \boldsymbol{\Sigma} \boldsymbol{w}}$.
- Plot the cloud of points, $\mu_{\Pi}$ vertically on $\sigma_{\Pi}$ horizontally. Explain this plot.

Hint: use the investment universe settings above, but the task is not optimisation, and no other formulae involved. Compute only what is asked in the question. 

**Question 5.** NASDAQ100 data provided (2017-2023) for you to implement the backtesting of 99\%/10day Value at Risk and report the following:

(a) The count and percentage of VaR breaches.

(b) The count of consecutive VaR breaches. (1, 1, 1 indicates two consecutive occurrences)

(c) Provide a plot which: identifies the breaches visually (crosses or other marks) and properly labels axis $\mathrm{X}$ with at least years.

(d) In your own words, describe the sequence of breaches caused by COVID pandemic news in 2020-Feb versus 2020-Mar.

$$
\operatorname{VaR}_{10 D, t}=\text { Factor } \times \sigma_{t} \times \sqrt{10}
$$

- Compute the rolling standard deviation $\sigma_{t}$ from 21 daily returns.
- Timescale of that $\sigma_{t}$ remains 'daily' regardless of how many returns are in the sample. To make projection, use the additivity of variance $\sigma_{10 D}=\sqrt{\sigma_{t}^{2} \times 10}$.
- A breach occurs when the forward realised 10-day return is below the $\mathrm{VaR}_{t}$ quantity.

$r_{10 D, t+10}<\operatorname{VaR}_{10 D, t} \quad$ means breach, given both numbers are negative.

VaR is fixed at time $t$ and compared to the return realised from $t$ to $t+10$, computed $\ln \left(S_{t+10} / S_{t}\right)$. Alternatively, you can compare to $\ln \left(S_{t+11} / S_{t+1}\right)$ but state this assumption in your report upfront.

**Question 6.** Re-implement backtesting using the method above, recompute $\mathrm{VaR}_{10 D, t}$ but, with the input of EWMA $\sigma_{t+1}^{2}$. Use the variance for the entire dataset to initialise the scheme.

$$
\sigma_{t+1 \mid t}^{2}=\lambda \sigma_{t \mid t-1}^{2}+(1-\lambda) r_{t}^{2}
$$

with $\lambda=0.72$ value set to minimise out of sample forecasting error.

Hint: computation of EWMA $\sigma_{t+1}^{2}$ is not sufficient, proceed to compute $\operatorname{VaR}_{10 D, t}$ and count breaches in VaR.

(a-c) Provide the same deliverables (a), (b) and (c) as in the previous Question.

(d) Briefly (3-4 lines) discuss the impact of $\lambda$ on smoothness of EWMA-predicted volatility.
